# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 689)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_Frame = QtWidgets.QFrame(Form)
        self.top_Frame.setMinimumSize(QtCore.QSize(0, 25))
        self.top_Frame.setStyleSheet("QFrame#top_Frame {\n"
"    background-color: rgb(200, 224, 228);\n"
"}\n"
"QToolButton::hover {\n"
"    background-color: rgb(121, 164, 172);\n"
"}\n"
"QToolButton {\n"
"    border: none;\n"
"}")
        self.top_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_Frame.setObjectName("top_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_Frame)
        self.horizontalLayout.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.top_Frame)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setStyleSheet("image: url(:/icons/icon/icon.ico);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.top_Frame)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(831, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.min_btn = QtWidgets.QToolButton(self.top_Frame)
        self.min_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.min_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_btn.setStyleSheet("")
        self.min_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/EpMinus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon)
        self.min_btn.setIconSize(QtCore.QSize(20, 20))
        self.min_btn.setObjectName("min_btn")
        self.horizontalLayout.addWidget(self.min_btn)
        self.max_btn = QtWidgets.QToolButton(self.top_Frame)
        self.max_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.max_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.max_btn.setStyleSheet("")
        self.max_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/EpFullScreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_btn.setIcon(icon1)
        self.max_btn.setIconSize(QtCore.QSize(20, 20))
        self.max_btn.setObjectName("max_btn")
        self.horizontalLayout.addWidget(self.max_btn)
        self.close_btn = QtWidgets.QToolButton(self.top_Frame)
        self.close_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("\n"
"QToolButton::hover {\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/EpClose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setIconSize(QtCore.QSize(20, 20))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addWidget(self.top_Frame)
        self.buttomFrame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttomFrame.sizePolicy().hasHeightForWidth())
        self.buttomFrame.setSizePolicy(sizePolicy)
        self.buttomFrame.setStyleSheet("QFrame#buttomFrame {\n"
"    background-color: rgb(48, 54, 67);\n"
"}")
        self.buttomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttomFrame.setObjectName("buttomFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttomFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tag_frame = QtWidgets.QFrame(self.buttomFrame)
        self.tag_frame.setMinimumSize(QtCore.QSize(0, 31))
        self.tag_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tag_frame.setStyleSheet("QToolButton {\n"
"    border: none;\n"
"}\n"
"QFrame#tag_frame {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton {\n"
"    background-color: rgb(236, 245, 255);\n"
"    border-radius: 5px;\n"
"    color: rgb(64, 158, 255);\n"
"    border: 0.5px solid rgb(64, 158, 255); \n"
"}\n"
"QToolButton::hover {\n"
"    background-color: rgb(64, 158, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.tag_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tag_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tag_frame.setObjectName("tag_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tag_frame)
        self.horizontalLayout_2.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.tag_frame)
        self.frame.setMinimumSize(QtCore.QSize(1000, 30))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("QPushButton {\n"
"    background-color: rgb(64, 158, 255);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(121, 187, 255);\n"
"    border-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.serial_config_btn = QtWidgets.QPushButton(self.frame)
        self.serial_config_btn.setGeometry(QtCore.QRect(0, 0, 75, 30))
        self.serial_config_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.serial_config_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serial_config_btn.setObjectName("serial_config_btn")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 0, 75, 30))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 0, 75, 30))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.frame)
        self.open_btn = QtWidgets.QToolButton(self.tag_frame)
        self.open_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/EpArrowRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_btn.setIcon(icon3)
        self.open_btn.setIconSize(QtCore.QSize(20, 20))
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout_2.addWidget(self.open_btn)
        self.verticalLayout_2.addWidget(self.tag_frame)
        self.main_frame = QtWidgets.QFrame(self.buttomFrame)
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.serial_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_frame.sizePolicy().hasHeightForWidth())
        self.serial_frame.setSizePolicy(sizePolicy)
        self.serial_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.serial_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serial_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.serial_frame.setObjectName("serial_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.serial_frame)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.serial_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.serial_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(64, 158, 255);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(121, 187, 255);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.clear_send_text = QtWidgets.QPushButton(self.frame_3)
        self.clear_send_text.setMinimumSize(QtCore.QSize(75, 30))
        self.clear_send_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_send_text.setObjectName("clear_send_text")
        self.horizontalLayout_5.addWidget(self.clear_send_text)
        self.clear_receive_text = QtWidgets.QPushButton(self.frame_3)
        self.clear_receive_text.setMinimumSize(QtCore.QSize(75, 30))
        self.clear_receive_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_receive_text.setObjectName("clear_receive_text")
        self.horizontalLayout_5.addWidget(self.clear_receive_text)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.check_time = CustomToggleButton(self.frame_3)
        self.check_time.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_time.setFont(font)
        self.check_time.setObjectName("check_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.check_time)
        self.check_hex_receive = CustomToggleButton(self.frame_3)
        self.check_hex_receive.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_hex_receive.setFont(font)
        self.check_hex_receive.setObjectName("check_hex_receive")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.check_hex_receive)
        self.check_loop_send = CustomToggleButton(self.frame_3)
        self.check_loop_send.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_loop_send.setFont(font)
        self.check_loop_send.setObjectName("check_loop_send")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.check_loop_send)
        self.check_hex_send = CustomToggleButton(self.frame_3)
        self.check_hex_send.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_hex_send.setFont(font)
        self.check_hex_send.setObjectName("check_hex_send")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.check_hex_send)
        self.check_save_log = CustomToggleButton(self.frame_3)
        self.check_save_log.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_save_log.setFont(font)
        self.check_save_log.setObjectName("check_save_log")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.check_save_log)
        self.check_enter = CustomToggleButton(self.frame_3)
        self.check_enter.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.check_enter.setFont(font)
        self.check_enter.setObjectName("check_enter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.check_enter)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.serial_frame)
        self.quick_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quick_frame.sizePolicy().hasHeightForWidth())
        self.quick_frame.setSizePolicy(sizePolicy)
        self.quick_frame.setMaximumSize(QtCore.QSize(180, 16777215))
        self.quick_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quick_frame.setStyleSheet("QFrame#quick_frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(64, 158, 255);\n"
"    border-radius: 3px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12px Microsoft YaHei;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(121, 187, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.quick_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quick_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quick_frame.setObjectName("quick_frame")
        self.horizontalLayout_3.addWidget(self.quick_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.buttomFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "PyCom V1.0.0"))
        self.serial_config_btn.setText(_translate("Form", "串口配置"))
        self.pushButton_2.setText(_translate("Form", "保存配置"))
        self.pushButton_5.setText(_translate("Form", "多指令发送"))
        self.label_3.setText(_translate("Form", "发送端"))
        self.pushButton.setText(_translate("Form", "发送"))
        self.clear_send_text.setText(_translate("Form", "清空接收区"))
        self.clear_receive_text.setText(_translate("Form", "清空发送区"))
        self.check_time.setText(_translate("Form", "加时间戳"))
        self.check_hex_receive.setText(_translate("Form", "hex接收"))
        self.check_loop_send.setText(_translate("Form", "循环发送"))
        self.check_hex_send.setText(_translate("Form", "hex发送"))
        self.check_save_log.setText(_translate("Form", "保存日志"))
        self.check_enter.setText(_translate("Form", "回车换行"))
from coustom_ui.checkbox import CustomToggleButton
from . import resources
