# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upgrade.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Upgrade_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.file_bin_path = QtWidgets.QLineEdit(self.frame)
        self.file_bin_path.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.file_bin_path.setFont(font)
        self.file_bin_path.setStyleSheet("QLineEdit {\n"
"    border-radius: 4px;\n"
"    border: 1px solid #ced4da;\n"
"}")
        self.file_bin_path.setObjectName("file_bin_path")
        self.verticalLayout_2.addWidget(self.file_bin_path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.get_bin_file = NewQPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_bin_file.sizePolicy().hasHeightForWidth())
        self.get_bin_file.setSizePolicy(sizePolicy)
        self.get_bin_file.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.get_bin_file.setFont(font)
        self.get_bin_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_bin_file.setObjectName("get_bin_file")
        self.horizontalLayout.addWidget(self.get_bin_file)
        self.start_upgrade_btn = NewQPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_upgrade_btn.sizePolicy().hasHeightForWidth())
        self.start_upgrade_btn.setSizePolicy(sizePolicy)
        self.start_upgrade_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.start_upgrade_btn.setFont(font)
        self.start_upgrade_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_upgrade_btn.setObjectName("start_upgrade_btn")
        self.horizontalLayout.addWidget(self.start_upgrade_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_bin_path.setPlaceholderText(_translate("Form", "选择需要升级的bin"))
        self.get_bin_file.setText(_translate("Form", "获取文本"))
        self.start_upgrade_btn.setText(_translate("Form", "开始执行"))
from coustom_ui.pushbutton import NewQPushButton
